export const userConst = {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  LOADING_USER: 'LOADING_USER',
  USER_LOADED: 'USER_LOADED',
};

export const PostsConst = {
  ADD_POST: 'ADD_POST',
  ADD_COMMENT: 'ADD_COMMENT',
  SET_POSTS: 'SET_POSTS',
  POST_CREATED: 'POST_CREATED',
  CREATING_POST: 'CREATING_POST',
};
